name: cashorbit
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^3.6.0
  flutter_dotenv: ^5.0.2
  simple_animations: ^5.0.2
  sa3_liquid: ^1.0.1
  intl: ^0.19.0
  animations: ^2.0.11
  flutter_sticky_header: ^0.6.5
  sticky_and_expandable_list: ^1.1.3
  fl_chart: ^0.69.0
  drift: ^2.20.3
  sqlite3_flutter_libs: ^0.5.24
  path_provider: ^2.1.4
  path: ^1.9.0
  math_expressions: ^2.6.0
  share_plus: ^10.0.2
  google_sign_in: ^6.2.1
  universal_html: ^2.2.4
  flutter_charset_detector: ^4.0.0
  file_picker:
    git:
      url: https://github.com/melWiss/flutter_file_picker.git
  auto_size_text: ^3.0.0
  shared_preferences: ^2.3.2
  csv: ^6.0.0
  shimmer: ^3.0.0
  carousel_slider: ^5.0.0
  url_launcher: ^6.3.0
  flutter_launcher_icons: ^0.14.1
  package_info_plus: ^8.0.2
  transparent_image: ^2.0.1
  pausable_timer: ^3.1.0+3
  animated_fractionally_sized_box: ^2.0.1
  flutter_local_notifications: ^17.2.3
  sliding_sheet:
    path: ./packages/sliding_sheet-0.5.2-modified/
  implicitly_animated_reorderable_list:
    path: ./packages/implicitly_animated_reorderable_list-0.4.2-modified/
  easy_localization: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: Avenir
      fonts:
        - asset: assets/fonts/AvenirLTStd-Roman.otf
        - asset: assets/fonts/AvenirLTStd-Black.otf
          weight: 700