name: sliding_sheet
description: A widget that can be dragged and scrolled in a single gesture and snapped to a list of extents.
version: 0.5.2
homepage: https://github.com/bxqm/sliding_sheet

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: